// Mocks generated by Mockito 5.1.0 from annotations
// in flutter_todo_app/test/notifier/location_search_form_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_todo_app/repository/location_search_repository.dart'
    as _i2;
import 'package:geocoding/geocoding.dart' as _i4;
import 'package:google_maps_flutter/google_maps_flutter.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [LocationSearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationSearchRepository extends _i1.Mock
    implements _i2.LocationSearchRepository {
  MockLocationSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Location>> getLocations(String? address) =>
      (super.noSuchMethod(Invocation.method(#getLocations, [address]),
              returnValue: Future<List<_i4.Location>>.value(<_i4.Location>[]))
          as _i3.Future<List<_i4.Location>>);
  @override
  _i3.Future<String?> getAddress(_i5.LatLng? latLng) =>
      (super.noSuchMethod(Invocation.method(#getAddress, [latLng]),
          returnValue: Future<String?>.value()) as _i3.Future<String?>);
}
